env:
    browser: true

plugins:
    - react

ecmaFeatures:
    arrowFunctions: true
    blockBindings: true
    classes: true
    defaultParams: true
    destructuring: true
    forOf: true
    jsx: true
    modules: true
    spread: true
    templateStrings: true
    experimentalObjectRestSpread: true

rules:
    comma-dangle: [2, "always-multiline"]
    no-cond-assign: 2
    no-console: 1
    no-constant-condition: 2
    no-dupe-args: 2
    no-dupe-keys: 2
    no-duplicate-case: 2
    no-empty: 2
    no-func-assign: 2
    no-sparse-arrays: 2
    no-unreachable: 2
    use-isnan: 2
    valid-typeof: 2

    accessor-pairs: 2
    complexity: [2, 5]
    curly: 2
    default-case: 2
    dot-notation: 2
    eqeqeq: 2
    guard-for-in: 2
    no-alert: 1
    no-caller: 2
    no-eq-null: 2
    no-extend-native: 2
    no-eval: 2
    no-extra-bind: 2
    no-fallthrough: 2
    no-magic-numbers: 2
    no-multi-spaces: 2
    no-multi-str: 2
    no-native-reassign: 2
    no-redeclare: 2
    no-useless-call: 2
    no-useless-concat: 2
    no-undef: 2
    no-unused-vars: [2, {"vars": "all", "args": "after-used", "varsIgnorePattern": "React"}]

    array-bracket-spacing: [2, "never"]
    block-spacing: 2
    brace-style: 2
    camelcase: 2
    comma-spacing: [2, {"before": false, "after": true}]
    indent: [2, 4, {"SwitchCase": 1}]
    key-spacing: [2, {"beforeColon": false, "afterColon": true}]
    max-depth: [2, 3]
    max-len: [2, 120]
    max-nested-callbacks: [2, 3]
    max-params: [2, 5]
    no-multiple-empty-lines: [2, {max: 2}]
    no-negated-condition: 2
    no-nested-ternary: 2
    no-new-object: 2
    no-spaced-func: 2
    no-trailing-spaces: 2
    semi: [2, "never"]
    space-after-keywords: 2
    space-before-blocks: 2
    space-before-function-paren: 2
    space-before-keywords: [2, "always"]
    space-in-parens: [2, "never"]
    space-return-throw-case: 2

    arrow-body-style: [2, "always"]
    arrow-parens: [2, "always"]
    arrow-spacing: 2
    constructor-super: 2
    no-class-assign: 2
    no-const-assign: 2
    no-dupe-class-members: 2
    no-this-before-super: 2
    no-var: 1
    object-shorthand: 2
    prefer-arrow-callback: 2
    prefer-const: 1
    prefer-spread: 2
    prefer-template: 2
